site_name: Sacloud ドキュメント
site_url: https://docs.usacloud.jp
site_description: Sacloudの提供するOSSツール群のドキュメント
site_author: '@yamamoto-febc'
copyright: Copyright (C) 2016-2019 sacloude authors
google_analytics: ['UA-63739336-5','auto']
theme: readthedocs
extra_css:
  - css/extra.css
nav:
  - 目次: index.md
  - Terraform: https://docs.usacloud.jp/terraform
  - Usacloud: https://sacloud.github.io/usacloud
