site_name: Sacloud ドキュメント
site_url: https://docs.usacloud.jp
site_description: Sacloudの提供するOSSツール群のドキュメント
site_author: '@yamamoto-febc'
repo_url: https://github.com/sacloud/
repo_name: github.com/sacloud
copyright: Copyright (C) 2016-2022 sacloud authors
theme:
  name: material
  language: ja
extra:
  analytics:
    provider: google
    property: UA-63739336-5
extra_css:
  - css/extra.css
nav:
  - 目次: index.md
