site_name: Sacloud ドキュメント
site_url: https://docs.usacloud.jp
site_description: Sacloudの提供するOSSツール群のドキュメント
site_author: '@yamamoto-febc'
copyright: Copyright (C) 2016-2020 sacloude authors
extra:
  analytics:
    provider: google
    property: UA-63739336-5
theme:
  name: readthedocs
  navigation_depth: 1
extra_css:
  - css/extra.css
nav:
  - 目次: index.md
  - Terraform: https://docs.usacloud.jp/terraform
  - Terraform(v1): https://docs.usacloud.jp/terraform-v1
  - Usacloud: https://docs.usacloud.jp/usacloud
  - Usacon: https://docs.usacloud.jp/usacon
  - AutoScaler: https://docs.usacloud.jp/autoscaler
