services: docker
language: minimal
env:
  global:
    secure: WRPyklf+6DWEPl+lIhBcA4ixgbCOP//sQrrTCa/9Q79ctdtIlxQ1RtAXyzIQyDvrIkriXXLPsAsBAYalr+dHyP4XPTmyB/POTZDNcRqJgh1XM9xXiWrcKKOFZ8P4+rtkzzgTmxxKk6wP1SU3wT+Pgbq0SSy0OGyFJRlLbmMZIPe7ekd43Za7lvDd6cBXGmv/VP9JdctqvV972D2tSDUtqO+uHhAHesssWhgbk+B1ZdwybKC14vyV73mpeArDr3dLwyP9GAAfa6xj7aER+wQT3VEO6D/1O2dpKryV7d7QD4oo0uvcKoMAE1YvLjhYEME4+82gAy/QH9yJoScuGyPhOyoAADc60A00MhTZu3S3ouptgC3iLIwKQIPsPeT9R3imrCgJqsYjMJ9FYvTa+40BsEZBZucO/4yMkH+tdfJHKU4xPi14FI2rE20QH2p2Ea5J0Pm/dpZKqozGtYTLv9tlQqkiJPzYjxFXYeEhCq302UHU7MOJjZLwX2n2kMETz15zZ8KtHQVelic9O+cBzIEXfWTHQhsPWaLDEoKSj3dP0MYVKbol0y8UDEFOX25N/3FbpWkhaV0fmef4blosdNNxnfvesr7Y0f5gODs6E/URRDiPX8bCg8TlqM3HqTAl+YbJ9yZkIw4CfHrATLTHkse7aRlF3elCCIQyr+5ILDt5Mgw=
script:
  - make lint
before_deploy:
  - make build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  target_branch: master
  fqdn: docs.usacloud.jp
  user: sacloud-bot
  email: sacloud.users@gmail.com
  on:
    branch: master
notifications:
  slack:
    secure: s3r6HpzsBRUT7rPjkzmoDrfPIvJlDDSP7HF6t+QF3SVIUV9rP31Ds+e/8xD3/iLAv2iajD85dN1MDNFAH+wQB8NPbpXHS5mgplO4DVmctT8+tc7kINKNxF5DasmKeu97Wlps0xNX8Du8zCKZZuvit5Y5kFVPpABkdAJe8hdJr6v2WB8DEOYoJ1z+lVviKGbz+BGX0ygp8pRcizdnAJWI/cI78nNgYQ6aTGmfqau37VLlCd5tq3eIRGnBGHqA9+mYtjBwQlFKj7xeOgwCVJF+9fsQC9iIkD36MxuXQoAHOGHkRORi5q828QZk2dPNP2u0S6Mr1IhqRoU9yCXzYJVOCxZHgtDdv/6+bUB9egi1eK/PMG5Z02LwcC0TBLMpwgWxgdhUYsYn4rlwXFaQwgLDhhWY2jAsL8ImEfw09p9XMY0k7bpehZz4k14BeQWUg4dJddDapACJbmQtK5IM7VwjqY9X5jSYTkQHh1Mq5Dl7iAX6lRHgrRwgQgKNUMPdWcdnsdqzj4irddQanorSiRhEhtUAoEjcPbjn/F8HXnbAYt0Va+YriqmzfsohG1rRZkc44O6tmU/H7J7qy2rLXZ4/9//qY5WmI39M38tWXMxxnR1gWj6qXzz6+OuWSoPuBTR0iqkx4+qytg8FNlV9Wkr2LE2SrKo6SG8ihBu4L/6GrTg=
