site_name: Usacloudドキュメント
site_url: https://sacloud.github.io/usacloud/
site_description: Usacloud日本語ドキュメント
site_author: '@sacloud-authors'
repo_url: https://github.com/sacloud/usacloud
repo_name: usacloud
copyright: Copyright (C) 2017-2020 The Usacloud Authors.
google_analytics: ['UA-63739336-5','auto']
theme: readthedocs
extra_css:
  - css/extra.css
markdown_extensions:
  - admonition
  - attr_list
  - codehilite
nav:
  - ホーム: index.md
  - インストール: installation/start_guide.md
  - アップグレード:
      - v1.0.0へのアップグレード: upgrade/v1_0_0.md
  - 利用方法/ガイド:
      - 基本的な使い方: guides/basic_usage.md
      - completionコマンド: guides/completion.md
      - restコマンド: guides/rest.md
  - リファレンス:
      - オプション/設定:
          - グローバルオプション: commands/global.md
          - プロファイル: commands/profile.md
      - コマンド:
          - Configuration / プロファイル/コンフィグ:
              - config: commands/config.md
          - Authentication / 認証情報:
              - auth-status: commands/auth-status.md
          - Computing / コンピューティング:
              - private-host: commands/private-host.md
              - server: commands/server.md
          - Storage / ストレージ:
              - archive: commands/archive.md
              - auto-backup: commands/auto-backup.md
              - cdrom: commands/cdrom.md
              - disk: commands/disk.md
          - Networking / ネットワーキング:
              - bridge: commands/bridge.md
              - internet: commands/internet.md
              - local-router: commands/local-router.md
              - packet-filter: commands/packet-filter.md
              - switch: commands/switch.md
          - ネットワーク関連サブリソース:
              - interface: commands/interface.md
              - ipaddress: commands/ipaddress.md
              - ipv6addr: commands/ipv6addr.md
              - ipv6net: commands/ipv6net.md
              - subnet: commands/subnet.md
          - Appliance / アプライアンス:
              - database: commands/database.md
              - load-balancer: commands/load-balancer.md
              - nfs: commands/nfs.md
              - vpc-router: commands/vpc-router.md
          - Secure Mobile / セキュアモバイル:
                - mobile-gateway: commands/mobile-gateway.md
                - sim: commands/sim.md
          - Common service items / 共通サービスアイテム:
              - dns: commands/dns.md
              - gslb: commands/gslb.md
              - proxy-lb: commands/proxy-lb.md
              - simple-monitor: commands/simple-monitor.md
          - Billing / 請求関連:
              - bill: commands/bill.md
              - coupon: commands/coupon.md
          - Lab / Labプロダクト:
              - container-registry: commands/container-registry.md
              - esme: commands/esme.md
          - WebAccelerator / ウェブアクセラレータ:
              - web-accelerator: commands/web-accelerator.md
          - Other services / その他サービス:
              - icon: commands/icon.md
              - license: commands/license.md
              - note: commands/note.md
              - ssh-key: commands/ssh-key.md
          - Region/Zone information / リージョン/ゾーン情報参照:
              - region: commands/region.md
              - zone: commands/zone.md
          - Service/Product information / サービス/プロダクト情報参照:
              - disk-plan: commands/disk-plan.md
              - internet-plan: commands/internet-plan.md
              - license-info: commands/license-info.md
              - private-host-plan: commands/private-host-plan.md
              - server-plan: commands/server-plan.md
              - service-class: commands/service-class.md
          - Other commands / その他:
              - completion: commands/completion.md
              - rest: commands/rest.md
              - self: commands/self.md