site_name: Terraform for さくらのクラウド
site_url: https://docs.usacloud.jp/terraform
site_description: Terrform for さくらのクラウド
site_author: '@yamamoto-febc'
copyright: Copyright (C) 2016-2019 terraform-provider-sakuracloud authors
google_analytics: ['UA-63739336-5','auto']
theme: readthedocs
extra_css:
  - css/extra.css
pages:
  - ホーム: index.md
  - ドキュメント:
    - インストールガイド: installation.md
    - アップグレードガイド:
      - v0.12での変更点: upgrade_to_v012.md
      - v1.1での変更点: upgrade_to_v11.md
      - v1.4での変更点: upgrade_to_v14.md
      - v1.6での変更点: upgrade_to_v16.md
      - v1.7での変更点: upgrade_to_v17.md
      - v1.11での変更点: upgrade_to_v1_11.md
      - v1.14での変更点: upgrade_to_v1_14.md
      - v1.15での変更点: upgrade_to_v1_15.md
    - ブログ/記事/読み物: articles.md
  - 設定リファレンス:
    - 全体/共通項目:
      - プロバイダ: configuration/provider.md
    - リソース:
      - サーバ: configuration/resources/server.md
      - ディスク: configuration/resources/disk.md
      - アーカイブ: configuration/resources/archive.md
      - ISOイメージ(CD-ROM): configuration/resources/cdrom.md
      - スイッチ: configuration/resources/switch.md
      - ルータ: configuration/resources/internet.md
      - サブネット: configuration/resources/subnet.md
      - パケットフィルタ: configuration/resources/packet_filter.md
      - パケットフィルタ(ルール): configuration/resources/packet_filter_rule.md
      - ブリッジ: configuration/resources/bridge.md
      - ロードバランサ: configuration/resources/load_balancer.md
      - VPCルータ: configuration/resources/vpc_router.md
      - VPCルータ(子リソース): configuration/resources/vpc_router_old.md
      - データベース: configuration/resources/database.md
      - データベース(リードレプリカ): configuration/resources/database_read_replica.md
      - NFS: configuration/resources/nfs.md
      - SIM: configuration/resources/sim.md
      - モバイルゲートウェイ: configuration/resources/mobile_gateway.md
      - スタートアップスクリプト: configuration/resources/note.md
      - 公開鍵: configuration/resources/ssh_key.md
      - 公開鍵(生成): configuration/resources/ssh_key_gen.md
      - アイコン: configuration/resources/icon.md
      - 専有ホスト: configuration/resources/private_host.md
      - DNS: configuration/resources/dns.md
      - IPv4逆引きレコード: configuration/resources/ipv4_ptr.md
      - エンハンスドロードバランサ: configuration/resources/proxylb.md
      - エンハンスドロードバランサ(Let's Encrypt設定): configuration/resources/proxylb_acme.md
      - GSLB: configuration/resources/gslb.md
      - シンプル監視: configuration/resources/simple_monitor.md
      - 自動バックアップ: configuration/resources/auto_backup.md
      - ウェブアクセラレータ(証明書): configuration/resources/webaccel_certificate.md
      - オブジェクトストレージ: configuration/resources/bucket_object.md
    - 特殊なリソース:
      - サーバ コネクタ: configuration/resources/server_connector.md
    - データリソース:
      - データリソースとは: configuration/resources/data_resource.md
      - サーバ: configuration/resources/data/server.md
      - ディスク: configuration/resources/data/disk.md
      - アーカイブ: configuration/resources/data/archive.md
      - ISOイメージ(CD-ROM): configuration/resources/data/cdrom.md
      - スイッチ: configuration/resources/data/switch.md
      - ルータ: configuration/resources/data/internet.md
      - サブネット: configuration/resources/data/subnet.md
      - パケットフィルタ: configuration/resources/data/packet_filter.md
      - ブリッジ: configuration/resources/data/bridge.md
      - ロードバランサ: configuration/resources/data/load_balancer.md
      - VPCルータ: configuration/resources/data/vpc_router.md
      - データベース: configuration/resources/data/database.md
      - NFS: configuration/resources/data/nfs.md
      - スタートアップスクリプト: configuration/resources/data/note.md
      - 公開鍵: configuration/resources/data/ssh_key.md
      - アイコン: configuration/resources/data/icon.md
      - 専有ホスト: configuration/resources/data/private_host.md
      - DNS: configuration/resources/data/dns.md
      - エンハンスドロードバランサ: configuration/resources/data/proxylb.md
      - GSLB: configuration/resources/data/gslb.md
      - シンプル監視: configuration/resources/data/simple_monitor.md
      - オブジェクトストレージ: configuration/resources/data/bucket_object.md
      - ウェブアクセラレータ(サイト): configuration/resources/data/webaccel.md
      - ゾーン: configuration/resources/data/zone.md
